# Generated by Django 5.1.11 on 2025-08-08 17:31

import django.db.models.deletion
import helpers.db.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subdomain', models.CharField(db_index=True, max_length=60, unique=True, validators=[helpers.db.validators.validate_subdomain, helpers.db.validators.validate_blocked_subdomains])),
                ('schema_name', models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('active_at', models.DateTimeField(blank=True, null=True)),
                ('inactive_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
