# Generated by Django 5.1.11 on 2025-08-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('VIN', models.CharField(max_length=17, unique=True)),
                ('year', models.IntegerField()),
                ('specs', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='vehicles/photos/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved')], max_length=20)),
            ],
        ),
    ]
